# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  roomservice:
    image: roomservice
    build:
      context: .
      dockerfile: RoomService/RoomService/Dockerfile
    ports:
      - 5000:5000
